name : Simple workflow

on : push

jobs:
    job1:
      name: Job 1
      runs-on: ubuntu-latest
      steps:
        - name: Step 1
        run: echo "Execution Job 1"
    
    job2:
      name: Job 2
      needs: job1
      runs-on: ubuntu-latest
      steps:
        - name: Step 2
        run: echo "Execution job 2"

